# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "blurbs", :force => true do |t|
    t.column "title",      :string
    t.column "body",       :text
    t.column "project_id", :integer
    t.column "position",   :integer
  end

  create_table "images", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "type",         :string
    t.column "belongsto_id", :integer
  end

  create_table "palettes", :force => true do |t|
    t.column "name",   :string
    t.column "light",  :string, :limit => 6
    t.column "dark",   :string, :limit => 6
    t.column "accent", :string, :limit => 6
    t.column "trim",   :string, :limit => 6
  end

  create_table "projects", :force => true do |t|
    t.column "name", :string
    t.column "body", :text
    t.column "slug", :string
  end

  create_table "sqlite_sequence", :id => false, :force => true do |t|
    t.column "name", :decimal
    t.column "seq",  :decimal
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
